FROM	debian

RUN		apt update && apt install -y git vim

RUN		git config --global user.name "Nathan Plouvier" && \
				git config --global user.email nathanplouvier60@gmail.com

CMD		["sh"]

# check de la configuration: git config --list
